"""Pydantic schemas for the planning pipeline artifacts.

Simplified per archei rules: structured output is minimal (only fields used
programmatically by code). Rich content lives in written documents (prd.md,
architecture.md) that downstream agents read via tools.
"""

from __future__ import annotations

from pydantic import BaseModel


class PRDOutput(BaseModel):
    """Minimal structured output from the product manager.

    The full PRD (must_have, nice_to_have, out_of_scope, assumptions, risks)
    lives in the written prd.md file. Downstream agents have Read tools and
    prd_path to access it.
    """

    summary: str  # One-line validated description
    acceptance_criteria: list[str]  # Programmatic: verifier, sprint planner


# Backward-compat alias — old code that imports PRD still works
PRD = PRDOutput


class ArchitectureOutput(BaseModel):
    """Minimal structured output from the architect.

    The full architecture (components, interfaces, decisions, file_changes_overview)
    lives in the written architecture.md file.
    """

    summary: str  # For sprint planner prompt header + DAGState


# Backward-compat alias
Architecture = ArchitectureOutput


class ReviewResult(BaseModel):
    """Tech lead review of the architecture."""

    approved: bool  # Programmatic gate
    feedback: str  # LLM context for architect revision


class IssueSkeleton(BaseModel):
    """Minimal structured issue stub from the sprint planner.

    Only fields used programmatically by code. Rich content (acceptance_criteria,
    testing_strategy, guidance details) is generated by the issue_writer, which
    has Read access to the full PRD and architecture documents.
    """

    name: str  # identification, git branches
    title: str  # display
    description: str = ""  # 2-3 sentence seed for issue_writer
    depends_on: list[str] = []  # programmatic: topo sort
    files_to_create: list[str] = []  # programmatic: conflict detection
    files_to_modify: list[str] = []  # programmatic: conflict detection
    needs_deeper_qa: bool = False  # programmatic: coding loop path
    estimated_scope: str = "medium"  # informational
    target_repo: str = ""  # multi-repo builds


# Backward-compat alias
PlannedIssue = IssueSkeleton


class SprintDecomposition(BaseModel):
    """Sprint planner output: issue skeletons + rationale."""

    issues: list[IssueSkeleton]
    rationale: str


# Legacy aliases kept for import compat — these types are no longer used
# but some test files may import them.
class IssueGuidance(BaseModel):
    """Deprecated — guidance fields are now flat on IssueSkeleton or in issue_writer."""

    needs_new_tests: bool = True
    estimated_scope: str = "medium"
    touches_interfaces: bool = False
    needs_deeper_qa: bool = False
    testing_guidance: str = ""
    review_focus: str = ""
    risk_rationale: str = ""


class PlanResult(BaseModel):
    """Final output of the planning pipeline."""

    prd: dict  # PRDOutput.model_dump()
    architecture: dict  # ArchitectureOutput.model_dump()
    review: dict  # ReviewResult.model_dump()
    issues: list[dict]  # IssueSkeleton dicts (enriched by issue_writer later)
    levels: list[list[str]]  # Parallel execution levels from topo sort
    file_conflicts: list[dict] = []  # Informational only — merger agent handles resolution
    artifacts_dir: str
    rationale: str
